apiVersion: v1
kind: ConfigMap
metadata:
  name: bblam-app-config
  namespace: default
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_CONNECTION: "sqlsrv"
  DB_HOST: "sqlserver-service"
  DB_PORT: "1433"
  DB_DATABASE: "LOGIN_TEST"
  LOG_CHANNEL: "stack"
  LOG_LEVEL: "info"
