apiVersion: v1
kind: ConfigMap
metadata:
  name: bblam-app-config
  namespace: default
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_DATABASE: "bblamtestdb"
  LOG_CHANNEL: "stack"
  LOG_LEVEL: "info"
