apiVersion: v1
kind: Secret
metadata:
  name: bblam-app-secrets
  namespace: default
type: Opaque
stringData:
  DB_USERNAME: "sa"
  DB_PASSWORD: "YourStrong@Password123"
  APP_KEY: "base64:MTM0MjdhODItMzYwNi00ZGYzLWE2MDQtYTgxZjQxN2MwYTFh"
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
